
<!DOCTYPE html>
<html lang="zxx">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="keywords" content="">
<meta name="description" content="">
<title>:: Jasim Technologies Private Limited ::</title>
<!--favicon-->
<link rel="shortcut icon" type="image/png" href="assets/images/favicon.png">
<!--bootstrap css-->
<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
<!--owl carousel css-->
<link rel="stylesheet" type="text/css" href="assets/css/owl.carousel.min.css">
<!--magnific popup css-->
<link rel="stylesheet" type="text/css" href="assets/css/magnific-popup.css">
<!--font awesome css-->
<link rel="stylesheet" type="text/css" href="assets/css/font-awesome.min.css">
<!--meanmenu css-->
<link rel="stylesheet" type="text/css" href="assets/css/meanmenu.css">
<!--animate css-->
<link rel="stylesheet" type="text/css" href="assets/css/animate.css">
<!--main css-->
<link rel="stylesheet" type="text/css" href="assets/css/style.css">
<!--responsive css-->
<link rel="stylesheet" type="text/css" href="assets/css/responsive.css">
</head>

<body>
<div class="sidebar-wrap">
  <div class="sidebar-inner">
    <div class="sidebar-close">
      <div class="sidebar-close-btn"> <i class="fa fa-times"></i> </div>
    </div>
    <div class="sidebar-content">
      <div class="sidebar-logo"> <a href="index.html"> <img class="img-fluid" src="assets/images/logo.png" alt="logo.png"> </a> </div>
      <div class="mobile-menu"></div>
      <div class="contact-info">
        <ul>
          <li><i class="fa fa-envelope"></i> hr@appsele.com</li>
          <li><i class="fa fa-phone"></i> 080-37836192</li>
        </ul>
      </div>
      <div class="social-icon">
        <ul>
          <li><span>Follow Us:</span></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a> </li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        </ul>
      </div>
      <div class="header-log-reg">
        <ul>
          <li><a href="http://www.appsele.com/webmail" target="_blank">Employee Login</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- start header-top-area -->
<header class="header-area">
  <div class="header-top-area">
    <div class="container">
      <div class="header-top-wrap"> 
        <!--start header contact info-->
        <div class="header-contact-info text-left">
          <ul>
            <li><i class="fa fa-envelope"></i> hr@appsele.com</li>
            <li><i class="fa fa-phone"></i> 080-37836192</li>
          </ul>
        </div>
        <!--end header contact info--> 
        <!--start header-top-social-->
        <div class="header-top-social text-right">
          <ul>
            <li><a href="#"><i class="fa fa-twitter"></i></a> </li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
          </ul>
        </div>
        <!--end header-top-social--> 
      </div>
    </div>
  </div>
  <!--end header-top-area--> 
  <!--start header-btm-area-->
  <div class="header-btm-area">
    <div class="container">
      <div class="main-menu-wrap"> 
        <!--start site logo-->
        <div class="site-logo"> <a class="logo" href="index.html"><img src="assets/images/logo.png" alt="logo"></a> </div>
        <!--end site logo--> 
        <!--start mainmenu-->
        <div class="main-menu-area text-right">
          <nav class="mainmenu">
            <ul>
              <li> <a class="active" href="index.html">Home</a></li>
              <li><a href="about-us.html">About Us</a></li>
              <li><a href="#">Services</a>
                <ul class="sub-menu">
                  <li><a href="mobile-apps-development.html">Mobile App Development</a></li>
                  <li><a href="cloud-services.html">Cloud Services</a></li>
                  <li><a href="iot-development.html">IOT Development</a></li>
                  <li><a href="application-development.html">Application Development</a></li>
                  <li><a href="cms-development.html">CMS Development</a></li>
                  <li><a href="software-development.html">Software Development</a></li>
                </ul>
              </li>
              <li><a href="#">Technologies</a>
                <ul class="sub-menu">
                  <li><a href="salesforce.html">Salesforce</a></li>
                  <li><a href="oracle.html">Oracle</a></li>
                  <li><a href="clinical-sas.html">Clinical SAS</a></li>
                  <li><a href="python.html">Python</a></li>
                  <li><a href="marketing.html">Digital Marketing</a></li>
                  <li><a href="sap.html">SAP</a></li>
                </ul>
              </li>
              <li><a href="#">Healthcare Provider</a>
                <ul class="sub-menu">
                  <li><a href="revenue-cycle-management.html">Revenue Cycle Management</a></li>
                  <li><a href="coding-health-information-management.html">Coding / Health Information Management (HIM)</a></li>
                </ul>
              </li>
              <li><a href="#">Healthcare Payer</a>
                <ul class="sub-menu">
                  <li><a href="medical-coding-services.html">Medical Coding Services</a></li>
                  <li><a href="claims-management.html">Claims Management</a></li>
                  <li><a href="member-management.html">Member Management</a></li>
                  <li><a href="provider-network-data-management.html">Provider Network Data Management</a></li>
                  <li><a href="value-added-services.html">Value Added Services</a></li>
                </ul>
              </li>
              <li><a href="careers.html">Careers</a></li>
              <li><a href="contact.html">Contact Us</a></li>
            </ul>
          </nav>
        </div>
        <!--end mainmenu--> 
        
        <!--start login registration btn-->
        <div class="header-log-reg text-right">
          <ul>
            <li><a href="http://www.appsele.com/webmail" target="_blank">Employee Login</a></li>
          </ul>
        </div>
        <!--end login registration btn--> 
        <!--start toggle button-->
        <div class="header-toggle-btn"> <a class="sidebar-toggle-btn"> <i class="fa fa-bars"></i> </a> </div>
        <!--end toggle button--> 
      </div>
    </div>
  </div>
</header>
<!--end header--> 
<!--start hero area-->
<section class="hero-area two">
  <div class="container">
    <div class="row"> 
      <!--start heading-->
      <div class="col-lg-10">
        <div class="caption-content two">
          <h4>Jasim Technologies Private Limited</h4>
          <h2>Mobile App Development</h2>
          <p>The power of Mobile apps is known to many and the main strongpoint about mobile applications is the productivity factor it brings to its users.</p>
          <ul>
            <li><a href="mobile-apps-development.html">Learn More</a></li>
          </ul>
        </div>
      </div>
      <!--end heading--> 
    </div>
  </div>
</section>
<!--end hero area--> 
<!--start about-area-->
<section class="about-area">
  <div class="container">
    <div class="row"> 
      <!--start about-img-->
      <div class="col-md-6">
        <div class="about-img"> <img src="assets/images/about-img-1.jpg" class="img-fluid" alt="image">
          <div class="about-img-inner"> <img src="assets/images/about-img-2.jpg" class="img-fluid" alt="image"> </div>
          <div class="about-img-two"> <img src="assets/images/about-img-3.jpg" class="img-fluid" alt="image"> </div>
        </div>
      </div>
      <!--end about-img--> 
      <!--start about-cont-->
      <div class="col-md-6">
        <div class="about-cont d-table">
          <div class="align-middle d-table-cell">
            <h4>about us</h4>
            <h2>Jasim Technologies Private Limited</h2>
            <p> Jasim Technologies is a software development provider company which is a highflier in implementing Digital Transformation. It is a flexible and one of the best global eminent experts in outsourcing the software development and web development.</p>
            <p>In our view, Digitization is not just about innovation, it helps in remolding the businesses in a new way of marketing in this digital world. It should involve a new way of delivering products and services by adopting distinctive marketing exposures to engage with customers effectively.</p>
            <div class="btn-default"> <a href="about-us.html">Learn More</a> </div>
          </div>
        </div>
      </div>
      <!--end about-cont--> 
    </div>
  </div>
</section>
<!--end about-area--> 
<!--start category area-->
<section class="category-area two bg-gray">
  <div class="container">
    <div class="row"> 
      <!--start heading-->
      <div class="col-lg-8 offset-lg-2">
        <div class="sec-heading text-center">
          <h4>Jasim Technologies</h4>
          <h2>Services</h2>
        </div>
      </div>
      <!--end heading--> 
    </div>
    <div class="row"> 
      <!--start category single -->
      <div class="col-lg-4 col-md-6">
        <div class="category-single two shadow-none">
          <div class="category-icon"> <img class="img-fluid" src="assets/images/icons/trust.svg" alt="image"> </div>
          <div class="category-cont">
            <h4><a href="mobile-apps-development.html">Mobile App Development</a></h4>
            <p>The power of Mobile apps is known to many and the main strongpoint about mobile applications is the productivity factor it brings to its users.</p>
          </div>
        </div>
      </div>
      <!--end category single --> 
      <!--start category single -->
      <div class="col-lg-4 col-md-6">
        <div class="category-single two shadow-none">
          <div class="category-icon"> <img class="img-fluid" src="assets/images/icons/profits.svg" alt="image"> </div>
          <div class="category-cont">
            <h4><a href="cloud-services.html">Cloud Services</a></h4>
            <p>A large number of enterprises view Cloud as an effective way to transform their business for competitive advantage and improved customer engagement.</p>
          </div>
        </div>
      </div>
      <!--end category single --> 
      <!--start category single -->
      <div class="col-lg-4 col-md-6">
        <div class="category-single two shadow-none">
          <div class="category-icon"> <img class="img-fluid" src="assets/images/icons/camera.svg" alt="image"> </div>
          <div class="category-cont">
            <h4><a href="iot-development.html">IOT Development</a></h4>
            <p>IOT, the concept that unites everyday objects using a medium called the Internet. You can literally see that in our day to day life almost all our electronic items.</p>
          </div>
        </div>
      </div>
      <!--end category single --> 
      <!--start category single -->
      <div class="col-lg-4 col-md-6">
        <div class="category-single two shadow-none">
          <div class="category-icon"> <img class="img-fluid" src="assets/images/icons/vector.svg" alt="image"> </div>
          <div class="category-cont">
            <h4><a href="application-development.html">Application Development</a></h4>
            <p>A software process, software lifecycle or software development done in a planned structured manner is application development.</p>
          </div>
        </div>
      </div>
      <!--end category single --> 
      <!--start category single -->
      <div class="col-lg-4 col-md-6">
        <div class="category-single two shadow-none">
          <div class="category-icon"> <img class="img-fluid" src="assets/images/icons/pencil-and-ruler.svg" alt="image"> </div>
          <div class="category-cont">
            <h4><a href="cms-development.html">CMS Development</a></h4>
            <p>As of today, there is a huge demand for CMS based websites. Businesses globally are coming forward to take advantage of Content Management System.</p>
          </div>
        </div>
      </div>
      <!--end category single --> 
      <!--start category single -->
      <div class="col-lg-4 col-md-6">
        <div class="category-single two shadow-none">
          <div class="category-icon"> <img class="img-fluid" src="assets/images/icons/binary-code.svg" alt="image"> </div>
          <div class="category-cont">
            <h4><a href="software-development.html">Software Development</a></h4>
            <p>We provide custom software application development services to our customers based on their requirements. Through our software development solutions.</p>
          </div>
        </div>
      </div>
      <!--end category single --> 
    </div>
  </div>
</section>
<!--end category area--> 
<!--start course area-->
<section class="course-area two">
  <div class="container">
    <div class="row"> 
      <!--start heading-->
      <div class="col-lg-8 offset-lg-2">
        <div class="sec-heading text-center">
          <h4>Jasim Technologies</h4>
          <h2>Technologies</h2>
        </div>
      </div>
      <!--end heading--> 
    </div>
    <div class="row"> 
      <!--start course card-->
      <div class="col-lg-4 col-md-6">
        <div class="course-card">
          <div class="course-thumbnail"> <a href="salesforce.html"> <img src="assets/images/course-3.jpg" class="img-fluid" alt="image"> </a> </div>
          <div class="course-content">
            <h3 class="course-title"> <a href="salesforce.html">Salesforce</a> </h3>
            <p>Salesforce is a cloud computing service as a software (SaaS) company that specializes in customer relationship management (CRM).</p>
          </div>
        </div>
      </div>
      <!--end course card--> 
      <!--start course card-->
      <div class="col-lg-4 col-md-6">
        <div class="course-card">
          <div class="course-thumbnail"> <a href="oracle.html"> <img src="assets/images/course-11.jpg" class="img-fluid" alt="image"> </a> </div>
          <div class="course-content">
            <h3 class="course-title"> <a href="oracle.html">Oracle</a> </h3>
            <p>Innovative has a wealth of experience acquired through years of Oracle project execution. We blend business and industry insight with technology.</p>
          </div>
        </div>
      </div>
      <!--end course card--> 
      <!--start course card-->
      <div class="col-lg-4 col-md-6">
        <div class="course-card">
          <div class="course-thumbnail"> <a href="clinical-sas.html"> <img src="assets/images/course-4.jpg" class="img-fluid" alt="image"> </a> </div>
          <div class="course-content">
            <h3 class="course-title"> <a href="clinical-sas.html">Clinical SAS</a> </h3>
            <p>SAS Clinical / Clinical SAS is the application of SAS technology to clinical domain for clinical trial data analysis in pharmaceutical/biotech.</p>
          </div>
        </div>
      </div>
      <!--end course card--> 
      <!--start course card-->
      <div class="col-lg-4 col-md-6">
        <div class="course-card">
          <div class="course-thumbnail"> <a href="python.html"> <img src="assets/images/course-9.jpg" class="img-fluid" alt="image"> </a> </div>
          <div class="course-content">
            <h3 class="course-title"> <a href="python.html">Python</a> </h3>
            <p>Jasim Technologies delivers a wide range of custom Python solutions, spanning sophisticated web portals and next gen apps.</p>
          </div>
        </div>
      </div>
      <!--end course card--> 
      <!--start course card-->
      <div class="col-lg-4 col-md-6">
        <div class="course-card">
          <div class="course-thumbnail"> <a href="marketing.html"> <img src="assets/images/course-5.jpg" class="img-fluid" alt="image"> </a> </div>
          <div class="course-content">
            <h3 class="course-title"> <a href="marketing.html">Digital Marketing</a> </h3>
            <p>Got a product or service? Don’t know how to market it? Not to worry, Jasim Technologies provides the complete funnel architecture.</p>
          </div>
        </div>
      </div>
      <!--end course card--> 
      <!--start course card-->
      <div class="col-lg-4 col-md-6">
        <div class="course-card">
          <div class="course-thumbnail"> <a href="sap.html"> <img src="assets/images/course-10.jpg" class="img-fluid" alt="image"> </a> </div>
          <div class="course-content">
            <h3 class="course-title"> <a href="sap.html">SAP</a> </h3>
            <p>The Financial Accounting (SAP FI) module in SAP is designed to capture organizations business transactions in a manner that will satisfy external.</p>
          </div>
        </div>
      </div>
      <!--end course card--> 
    </div>
  </div>
</section>
<!--end course area--> 

<!--start testimonial area-->
<section class="testimonial-area two">
  <div class="container">
    <div class="row"> 
      <!--start sec-heading-->
      <div class="col-lg-8 offset-lg-2">
        <div class="sec-heading text-center">
          <h4>Jasim Technologies</h4>
          <h2>What Says Our Clients</h2>
        </div>
      </div>
      <!--end sec-heading--> 
    </div>
    <div class="testi-carousel owl-carousel"> 
      <!--start testimonial single-->
      <div class="testi-single two">
        <div class="testi-cont-inner">
          <div class="testi-quote"> <i class="fa fa-quote-left"></i> </div>
          <div class="testi-rating"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
          <p>We have worked with Vishleshan Technologies on various projects, and find that they provide quality service.</p>
        </div>
        <div class="testi-client-info">
          <div class="testi-client-img"> <img src="assets/images/test-1.png" alt="image"> </div>
          <div class="testi-client-details">
            <h4>Arun</h4>
            <h6>CEO</h6>
          </div>
        </div>
      </div>
      <!--end testimonial single--> 
      <!--start testimonial single-->
      <div class="testi-single two">
        <div class="testi-cont-inner">
          <div class="testi-quote"> <i class="fa fa-quote-left"></i> </div>
          <div class="testi-rating"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
          <p>Under tight deadlines and with high expectations, Jasim Technologies was a pleasure to partner with, on a high profile.</p>
        </div>
        <div class="testi-client-info">
          <div class="testi-client-img"> <img src="assets/images/test-1.png" alt="image"> </div>
          <div class="testi-client-details">
            <h4>Sagar</h4>
            <h6>Web Developer</h6>
          </div>
        </div>
      </div>
      <!--end testimonial single--> 
      <!--start testimonial single-->
      <div class="testi-single two">
        <div class="testi-cont-inner">
          <div class="testi-quote"> <i class="fa fa-quote-left"></i> </div>
          <div class="testi-rating"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
          <p>We have been using Jasim Technologies service for the last four months for testing of our Mobile app testing.</p>
        </div>
        <div class="testi-client-info">
          <div class="testi-client-img"> <img src="assets/images/test-1.png" alt="image"> </div>
          <div class="testi-client-details">
            <h4>Joythi</h4>
            <h6>HR Manager</h6>
          </div>
        </div>
      </div>
      <!--end testimonial single--> 
      <!--start testimonial single-->
      <div class="testi-single two">
        <div class="testi-cont-inner">
          <div class="testi-quote"> <i class="fa fa-quote-left"></i> </div>
          <div class="testi-rating"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
          <p>They have been a professional and committed partner Professional It is rare to find a service</p>
        </div>
        <div class="testi-client-info">
          <div class="testi-client-img"> <img src="assets/images/test-1.png" alt="image"> </div>
          <div class="testi-client-details">
            <h4>Kumar</h4>
            <h6>Apps Developer</h6>
          </div>
        </div>
      </div>
      <!--end testimonial single--> 
    </div>
  </div>
</section>
<!--end testimonial area--> 

<!--start footer-area-->
<footer class="footer-area"> 
  <!--start footer top area-->
  <div class="footer-top-area">
    <div class="container">
      <div class="row"> 
        <!--start footer widget-->
        <div class="col-lg-4 col-md-6">
          <div class="footer-widget logo"> <a href="#"><img src="assets/images/logo-white-1.png" alt="logo"></a>
            <div class="footer-about-description">
              <p>Jasim Technologies is a software development provider company which is a highflier in implementing Digital Transformation. It is a flexible and one of the best global eminent experts in outsourcing the software development and web development.</p>
            </div>
          </div>
        </div>
        <!--end footer widget--> 
        <!--start footer widget-->
        <div class="col-lg-3 col-md-6">
          <div class="footer-widget footer-cat">
            <h4>Services</h4>
            <ul>
              <li><a href="mobile-apps-development.html"><i class="fa fa-angle-right"></i> Mobile App Development</a></li>
              <li><a href="cloud-services.html"><i class="fa fa-angle-right"></i> Cloud Services</a></li>
              <li><a href="iot-development.html"><i class="fa fa-angle-right"></i> IOT Development</a></li>
              <li><a href="application-development.html"><i class="fa fa-angle-right"></i> Application Development</a></li>
              <li><a href="cms-development.html"><i class="fa fa-angle-right"></i> CMS Development</a></li>
              <li><a href="software-development.html"><i class="fa fa-angle-right"></i> Software Development</a></li>
            </ul>
          </div>
        </div>
        <!--end footer widget--> 
        <!--start footer widget-->
        <div class="col-lg-2 col-md-6">
          <div class="footer-widget recent-post">
            <h4> Technologies</h4>
            <ul>
              <li><a href="salesforce.html"><i class="fa fa-angle-right"></i> Salesforce</a></li>
              <li><a href="oracle.html"><i class="fa fa-angle-right"></i> Oracle</a></li>
              <li><a href="clinical-sas.html"><i class="fa fa-angle-right"></i> Clinical SAS</a></li>
              <li><a href="python.html"><i class="fa fa-angle-right"></i> Python</a></li>
              <li><a href="marketing.html"><i class="fa fa-angle-right"></i> Digital Marketing</a></li>
              <li><a href="sap.html"><i class="fa fa-angle-right"></i> SAP</a></li>
            </ul>
          </div>
        </div>
        <!--end footer widget--> 
        <!--start footer widget-->
        <div class="col-lg-3 col-md-6">
          <div class="footer-widget footer-contact">
            <h4>Contact Us</h4>
            <ul>
              <li> <i class="fa fa-map-marker"></i>
                <p class="m-0">#334, 27th Main Road, 2nd Sector HSR Layout, Bangalore -560102.</p>
              </li>
              <li> <i class="fa fa-envelope" aria-hidden="true"></i>
                <p class="m-0">hr@appsele.com</p>
              </li>
              <li> <i class="fa fa-phone" aria-hidden="true"></i>
                <p class="m-0">080-37836192</p>
              </li>
            </ul>
            <h6 style="color: #fff;">Follow Us</h6>
            <ul class="footer-social-icons">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
        <!--end footer widget--> 
      </div>
    </div>
  </div>
  <!--end footer top area--> 
  <!--start footer bottom-->
  <div class="footer-bottom-area text-center">
    <div class="container">
      <p class="m-0">&copy; Copy 2023 Jasim Technologies Private Limited. All Rights Reserved</p>
    </div>
  </div>
  <!--end footer bottom--> 
</footer>
<!--end footer--> 
<!--jQuery js--> 
<script src="assets/js/jquery-3.3.1.min.js"></script> 
<!--proper js--> 
<script src="assets/js/popper.min.js"></script> 
<!--bootstrap js--> 
<script src="assets/js/bootstrap.min.js"></script> 
<!--mainmenu js--> 
<script src="assets/js/meanmenu.min.js"></script> 
<!--counterup js--> 
<script src="assets/js/counterup.min.js"></script> 
<!--waypoints js--> 
<script src="assets/js/waypoints.js"></script> 
<!--magnic popup js--> 
<script src="assets/js/magnific-popup.min.js"></script> 
<!--owl carousel js--> 
<script src="assets/js/owl.carousel.min.js"></script> 
<!--syotimer js--> 
<script src="assets/js/syotimer.min.js"></script> 
<!--main js--> 
<script src="assets/js/custom.js"></script>
</body>
</html>
